# ################################
# Model: Speaker Verification Baseline
# Authors: Hwidong Na 2020
#          Mirco Ravanelli 2020
# ################################

seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Folders and train_log file
voxceleb_source:
enroll_dir: !PLACEHOLDER #e.g., /localscratch/voxceleb1
test_dir: !PLACEHOLDER #e.g., /localscratch/voxceleb1
output_folder: results/aishell_eer/speaker_verification_ecapa_small
save_folder: !ref <output_folder>/save/
device: 'cuda:0'


# Here, the pretrained embedding model trained with train_speaker_embeddings.py hparams/train_ecapa_tdnn.yaml
# is downloaded from the speechbrain HuggingFace repository.
# However, a local path pointing to a directory containing your checkpoints may also be specified
# instead (see pretrainer below)
#pretrain_path: /home/smg/miao/speech_brain/speechbrain/recipes/VoxCeleb/SpeakerRec/results/ecapa_small_augment/1986/save/CKPT+2021-12-16+21-38-57+00/
pretrain_path: /home/smg/miao/speech_brain/speechbrain/recipes/VoxCeleb/cnceleb/results/ecapa_small_augment/1986/save/CKPT+2022-01-24+07-29-28+00
# csv files
enrol_data: !ref <save_folder>/enrol.csv
test_data: !ref <save_folder>/test.csv

batch_size: 8

# Feature parameters
n_mels: 80
left_frames: 0
right_frames: 0
deltas: False

# Dataloader options
train_dataloader_opts:
    batch_size: !ref <batch_size>

enrol_dataloader_opts:
    batch_size: !ref <batch_size>

test_dataloader_opts:
    batch_size: !ref <batch_size>

compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    std_norm: False

embedding_model: !new:speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNN
    input_size: !ref <n_mels>
    channels: [512, 512, 512, 512, 1536]
    kernel_sizes: [5, 3, 3, 3, 1]
    dilations: [1, 2, 3, 4, 1]
    groups: [1, 1, 1, 1, 1]
    attention_channels: 128
    lin_neurons: 192

mean_var_norm_emb: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
    std_norm: False

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
        embedding_model: !ref <embedding_model>
    paths:
        embedding_model: !ref <pretrain_path>/embedding_model.ckpt
